/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smile_food;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author user
 */
public class Admin extends javax.swing.JFrame implements MouseListener, ActionListener {

    /**
     * Creates new form Admin
     */
        JPanel pcenter;
	JTable jt;
	MonModel2 model;
	ResultSet rs;
	Statement st;
	JMenuItem supp,show;
        
    public Admin() {
              this.setSize(700, 700);
	
		pcenter=new JPanel(new FlowLayout());
		jt=new JTable();

		pcenter.add(new JScrollPane(jt),BorderLayout.CENTER);
		this.add(pcenter);

		MaConnection con=new MaConnection();

		String rqt="Select * from client";
		rs=con.select(rqt);
		model=new MonModel2(rs);
		jt.setModel(model);
		
		/*JPanel pwest=new JPanel(new BorderLayout());
		JButton supprimer=new JButton("supp");
		pwest.add(supprimer,BorderLayout.SOUTH);
		JButton sh=new JButton("show");
		pwest.add(sh,BorderLayout.SOUTH);
		*/
		
		jt.addMouseListener(this);
                /*
                show.addMouseListener(this);
                supp.addMouseListener(this);*/
	}
	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
   
   

   
    
    
 @Override
    public void actionPerformed(ActionEvent e) {
if(e.getSource()==supp){
                    jt.removeAll();
                    
                    // ==>delete
                }      
           if(e.getSource()==show){
               //C:\Users/user\Desktop\Smile_food\fichier.html
           // ==>fichier.html           
           }         }
    @Override
    public void mouseClicked(MouseEvent e) {


		if(e.getSource()==jt){

			if(e.getButton()==MouseEvent.BUTTON3){
                            
				JPopupMenu menu = new JPopupMenu () ;
				supp=new JMenuItem("delete");
				show=new JMenuItem("show details");

				menu.add(supp);
				menu.add(show);

				menu.show(jt,e.getX(),e.getY());
				supp.addActionListener(this);
                                show.addActionListener(this);
                                


			
		}
    }    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
      
     /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
