/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smile_food;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JCheckBox;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {
 int montant;
     int montant1;
    int montant2;
    int montant3;
    int montant4;
    int montant5;
    int montant6;
    int montant7;
    int montant8;
    int montant9;
    int montant10;
    int montant11;
    File f;
    FileWriter fw;
    BufferedWriter bw;
     int mont;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        escth = new javax.swing.JLabel();
        kms = new javax.swing.JLabel();
        piz = new javax.swing.JLabel();
        pepeau = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        koskos = new javax.swing.JCheckBox();
        nbrek = new javax.swing.JTextField();
        k = new javax.swing.JLabel();
        fruit = new javax.swing.JCheckBox();
        escalope = new javax.swing.JCheckBox();
        eau = new javax.swing.JCheckBox();
        nbrepm = new javax.swing.JTextField();
        pfm = new javax.swing.JLabel();
        nbresc = new javax.swing.JTextField();
        esc = new javax.swing.JLabel();
        nbree = new javax.swing.JTextField();
        e = new javax.swing.JLabel();
        makarouna = new javax.swing.JCheckBox();
        fromage = new javax.swing.JCheckBox();
        tho = new javax.swing.JCheckBox();
        pepsi = new javax.swing.JCheckBox();
        nbrem = new javax.swing.JTextField();
        nbrepf = new javax.swing.JTextField();
        nbrethon = new javax.swing.JTextField();
        nbrep = new javax.swing.JTextField();
        m = new javax.swing.JLabel();
        pf = new javax.swing.JLabel();
        th = new javax.swing.JLabel();
        pep = new javax.swing.JLabel();
        salade = new javax.swing.JCheckBox();
        thon = new javax.swing.JCheckBox();
        jambon = new javax.swing.JCheckBox();
        boga = new javax.swing.JCheckBox();
        nbres = new javax.swing.JTextField();
        nbrepth = new javax.swing.JTextField();
        nbrej = new javax.swing.JTextField();
        nbreb = new javax.swing.JTextField();
        s = new javax.swing.JLabel();
        pth = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        bo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label_mont = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        txt_montant = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        back = new javax.swing.JButton();
        btnValider = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        nCard = new javax.swing.JTextField();
        pay = new javax.swing.JButton();
        wel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2000, 2000));

        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 2000));

        escth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile_food/pizza.jpg"))); // NOI18N

        kms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile_food/pizza.jpg"))); // NOI18N

        piz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile_food/lib.jpg"))); // NOI18N

        pepeau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile_food/lib.jpg"))); // NOI18N

        koskos.setText("Koskos");

        k.setText("7500");

        fruit.setText("Pizza Seaf Fruit");

        escalope.setText("Lebanese Escalopes");

        eau.setText("Water 1.5 L");

        pfm.setText("12000");

        esc.setText("3500");

        e.setText("  1500");

        makarouna.setText("Spaghetti");

        fromage.setText("Pizza Cheese");

        tho.setText("Lebanese Thon");

        pepsi.setText("Pepsi 0.5 L");

        nbrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbrepActionPerformed(evt);
            }
        });

        m.setText("7000");

        pf.setText("8000");

        th.setText("2500");

        pep.setText("2000");

        salade.setText("Salad");
        salade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladeActionPerformed(evt);
            }
        });

        thon.setText("Pizza Thonon");

        jambon.setText("Lebanese  Jambon");

        boga.setText("Boga 0.5 L");

        nbres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbresActionPerformed(evt);
            }
        });

        s.setText("6000");

        pth.setText("6000");

        jam.setText("2300");

        bo.setText("1500");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(fruit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nbrepm, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(koskos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nbrek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pfm)
                                    .addComponent(k)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addComponent(nbree, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(nbresc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(esc, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(e)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromage)
                            .addComponent(tho)
                            .addComponent(makarouna)
                            .addComponent(pepsi))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(nbrem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(nbrepf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pf))
                            .addComponent(nbrep, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(escalope)
                            .addComponent(eau))
                        .addGap(204, 204, 204)
                        .addComponent(nbrethon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(th)
                            .addComponent(pep))))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jambon)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nbrej, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(thon)
                                .addComponent(salade))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nbrepth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nbres, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(boga)
                        .addGap(30, 30, 30)
                        .addComponent(nbreb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(s))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jam)
                            .addComponent(pth)
                            .addComponent(bo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koskos)
                    .addComponent(nbrek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(k)
                    .addComponent(makarouna)
                    .addComponent(nbrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m)
                    .addComponent(salade)
                    .addComponent(nbres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s))
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fruit)
                    .addComponent(nbrepm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfm)
                    .addComponent(fromage)
                    .addComponent(nbrepf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf)
                    .addComponent(thon)
                    .addComponent(nbrepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pth))
                .addGap(89, 89, 89)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escalope)
                    .addComponent(nbresc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esc)
                    .addComponent(tho)
                    .addComponent(nbrethon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(th)
                    .addComponent(jambon)
                    .addComponent(nbrej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jam))
                .addGap(97, 97, 97)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eau)
                    .addComponent(nbree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e)
                    .addComponent(pepsi)
                    .addComponent(nbrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pep)
                    .addComponent(boga)
                    .addComponent(nbreb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bo))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        label_mont.setText("Amount");

        jLabel9.setText("Payment");

        jRadioButton1.setText("Species");

        txt_montant.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txt_montantMouseMoved(evt);
            }
        });

        jRadioButton2.setText("Credit Card");

        jRadioButton3.setText("Check");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        btnValider.setText("Save");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setText("CIN");

        jLabel19.setText("Card Number");

        nCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nCardActionPerformed(evt);
            }
        });

        pay.setText("Payment");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_mont)
                    .addComponent(jLabel9))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(back))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(35, 35, 35)
                                .addComponent(jRadioButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnValider)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))))
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nCard, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pay))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(txt_montant, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_montant, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_mont))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jLabel9))
                                .addGap(4, 4, 4)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(nCard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(back)
                            .addComponent(btnValider)
                            .addComponent(jButton4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(pay)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(escth)
                            .addComponent(kms)
                            .addComponent(piz)
                            .addComponent(pepeau))
                        .addGap(38, 38, 38)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1147, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(escth)
                        .addGap(18, 18, 18)
                        .addComponent(piz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pepeau))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        wel.setText("Welcome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1054, 1054, 1054)
                        .addComponent(wel)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1019, Short.MAX_VALUE))
        );

        //Client client =new client(nomprenom);
        String txt_nom="ikram";
        wel.setText("Welcome" + " " +txt_nom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2511, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nbrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbrepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbrepActionPerformed

    private void saladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saladeActionPerformed

    private void nbresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbresActionPerformed

    private void nCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nCardActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_montantMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_montantMouseMoved

                        int kos=Integer.parseInt(k.getText());
			int knb=Integer.parseInt(nbrek.getText());
			if((koskos.isSelected())&& !(nbrek.getText().equals(""))){
                           montant=Integer.valueOf(kos * knb);
                            txt_montant.setText(""+montant);

                        }
                        

                        
                                    else{
                           montant=Integer.valueOf(0);
                           txt_montant.setText(""+montant);

                                    }
                        
                        int mnb=Integer.parseInt(nbrem.getText());
			int mak=Integer.parseInt(m.getText());
                        if(makarouna.isSelected()&& !(nbrem.getText().equals(""))){    
			 montant1=Integer.valueOf(mnb * mak);
                        txt_montant.setText(montant1 + montant +"");

                        }

                      
                         else{
                           montant1=Integer.valueOf(0);
                           txt_montant.setText(""+montant1);

                        }
                        
                        
			int snb=Integer.parseInt(nbres.getText());
                         int sal=Integer.parseInt(s.getText());

                        if(salade.isSelected()&& !(nbres.getText().equals(""))){
                          montant2=Integer.valueOf(sal * snb );
                     txt_montant.setText(montant2+montant1 + montant +"");

                        }
 else{
                           montant2=Integer.valueOf(0);
                           txt_montant.setText(""+montant2);

                        }
                        
                        
                       int pfruit=Integer.parseInt(pfm.getText());
		       int pfmnb=Integer.parseInt(nbrepm.getText());
                        if(fruit.isSelected() ){
                          montant3=Integer.valueOf(pfruit * pfmnb );
                     txt_montant.setText(montant3+montant2+montant1 + montant +"");

                        }

                         else{
                           montant3=Integer.valueOf(0);
                           txt_montant.setText(""+montant3);

                        }
                        
                        
                        int pfromage=Integer.parseInt(pf.getText());
			int pfnb=Integer.parseInt(nbrepf.getText());
                        if(fromage.isSelected()){
                         montant4=Integer.valueOf(pfromage * pfnb );
                         txt_montant.setText(montant4 + montant3+montant2+montant1 + montant +"");

                        }

                        
                        
                        int pthon=Integer.parseInt(pth.getText());
			int pthnb=Integer.parseInt(nbrepth.getText());
                        if(thon.isSelected()){
                             montant5=Integer.valueOf(pthon *  pthnb );
                         txt_montant.setText(montant5+montant4 + montant3+montant2+montant1 + montant +"");

                        }

                        
                        int besc=Integer.parseInt(esc.getText());
			int escnb=Integer.parseInt(nbresc.getText());
                        if(escalope.isSelected()){
                            montant6=Integer.valueOf(besc * escnb );
                         txt_montant.setText(montant6+montant5+montant4 + montant3+montant2+montant1 + montant +"");

                        }
                        
                        
                         int bth=Integer.parseInt(th.getText());
			int thnb=Integer.parseInt(nbrethon.getText());

                        if(tho.isSelected()){
                         montant7=Integer.valueOf(bth *  thnb );
                        txt_montant.setText(montant7+montant6+montant5+montant4 + montant3+montant2+montant1 + montant +"");

                        }

                        
                        int bjam=Integer.parseInt(jam.getText());
			int jnb=Integer.parseInt( nbrej.getText());
                        if(jambon.isSelected()){
                         montant8=Integer.valueOf(bjam * jnb);
                          txt_montant.setText(montant8+montant7+montant6+montant5+montant4 + montant3+montant2+montant1 + montant +"");

                        }
			     //txt_montant.setText(""+montant8);

                        
                        int eauu=Integer.parseInt(e.getText());
			int enb=Integer.parseInt(nbree.getText());

			if(eau.isSelected()){
                       montant9=Integer.valueOf(eauu *  enb );
                         txt_montant.setText(montant9+montant8+montant7+montant6+montant5+montant4 + montant3+montant2+montant1 + montant +"");

                        }
                            //txt_montant.setText(""+montant9);

                        
                        
                        int pnb=Integer.parseInt(nbrep.getText());
                        int pepsii=Integer.parseInt(pep.getText());

                        if(pepsi.isSelected()){
                         montant10=Integer.valueOf(pnb * pepsii );
                         txt_montant.setText( montant10+montant9+montant8+montant7+montant6+montant5+montant4 + montant3+montant2+montant1 + montant +"");

                        }
                      //txt_montant.setText(""+montant10);

                        
                        
                        int bogaa=Integer.parseInt(bo.getText());
			int bnb=Integer.parseInt(nbreb.getText());

                        if(boga.isSelected()){
                         montant11=Integer.valueOf(bogaa * bnb );
                         txt_montant.setText( montant11+montant10+montant9+montant8+montant7+montant6+montant5+montant4 + montant3+montant2+montant1 + montant +"");

                        }

			//int mont=montant; 
                        String  mont1=String.valueOf(montant + montant1 + montant2 + montant3 + montant4 + montant5 + montant6 + montant7 + montant8 + montant9 + montant10 + montant11);
                                txt_montant.setText(mont1+"");
  

                        
			                 // TODO add your handling code here:
    }//GEN-LAST:event_txt_montantMouseMoved

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
    
			try{
                             f = new File("fichier.html");
                             fw = new FileWriter(f,false);
                             bw = new BufferedWriter(fw);

				
				bw.write("<html><fieldset><legend></legend>");
				
				
                      //bw.write(" Nom:"+client.getNomprenom()+"<br>");
   
				 bw.write(" Nom:<br>");
                                // Register register=new Register();
                                 //String nomprenom=register.txt_nomp.getText();
                                 //client=new Client(txt_nomp);//,phone,email,addr);
                                // bw.write("<html> Nom:"+nomprenom+" <br> </html>");
				
                                 String categ1=getKoskos().getLabel();
                                 String categ2=getMakarouna().getLabel();
                                 String categ3=getSalade().getLabel();
                                 String categ4=getFruit().getLabel();
                                 String categ5=getFromage().getLabel();
                                 String categ6=getThon().getLabel();
                                 String categ7=getEscalope().getLabel();
                                 String categ8=getTho().getLabel();
                                 String categ9=getJambon().getLabel();
                                 String categ10=getEau().getLabel();
                                 String categ11=getPepsi().getLabel();
                                 String categ12=getBoga().getLabel();
                                //String nbreko=nbrek.getText();
                                  //String mont=txt_montant.getText();

                                  if(koskos.isSelected()){
				bw.write(" "+categ1+" <br> ");	
				}	 
                                
				
				if(makarouna.isSelected()){
				bw.write(" "+categ2+" <br> ");	
                                }
                                
				if(salade.isSelected()){
                               bw.write(" "+categ3+" <br> ");	
}

				if(fruit.isSelected()){
				bw.write(" "+categ4+" <br> ");	

				}
				
				
				if(fromage.isSelected()){
				bw.write(" "+categ5+" <br> ");	

	
				}

				if(thon.isSelected()){
				bw.write(" "+categ6+" <br> ");	

				}

				if(escalope.isSelected()){
				bw.write(" "+categ7+" <br>");	
	
				}

				if(tho.isSelected()){
				bw.write(" "+categ8+" <br>");	
				}

				if(jambon.isSelected()){
				bw.write(" "+categ9+" <br>");	

				}
				
				
				if(pepsi.isSelected()){
				bw.write(" "+categ10+" <br>");	

				}
				
				if(eau.isSelected()){
				bw.write(" "+categ11+" <br> ");	

				}
				
				if(boga.isSelected()){
				bw.write(" "+categ12+" <br> ");	

				}
				//bw.write("Amount:"+" "+txt_montant+" <br> </html>");	

				bw.write("</fieldset></html>");
				//bw.write("</html>");
				bw.close();
				fw.close();

			}catch(IOException e){
				System.out.println("ERREUR");

			}         // TODO add your handling code here:
    }//GEN-LAST:event_btnValiderActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
cin.setEnabled(false);
nCard.setEnabled(false);
    }//GEN-LAST:event_payActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
Login l= new Login();
l.setVisible(true);          
// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public JTextField getNbreb() {
        return nbreb;
    }

    public JTextField getNbree() {
        return nbree;
    }

    public JTextField getNbrej() {
        return nbrej;
    }

    public JTextField getNbrek() {
        return nbrek;
    }

    public JTextField getNbrem() {
        return nbrem;
    }

    public JTextField getNbrep() {
        return nbrep;
    }

    public JTextField getNbrepf() {
        return nbrepf;
    }

    public JTextField getNbrepm() {
        return nbrepm;
    }

    public JTextField getNbrepth() {
        return nbrepth;
    }

    public JTextField getNbres() {
        return nbres;
    }

    public JTextField getNbresc() {
        return nbresc;
    }

    public JTextField getNbrethon() {
        return nbrethon;
    }

    public JTextField getTxt_montant() {
        return txt_montant;
    }

    public JCheckBox getKoskos() {
        return koskos;
    }

    public JCheckBox getBoga() {
        return boga;
    }

    public JCheckBox getEau() {
        return eau;
    }

    public JCheckBox getEscalope() {
        return escalope;
    }

    public JCheckBox getFromage() {
        return fromage;
    }

    public JCheckBox getFruit() {
        return fruit;
    }

    public JCheckBox getJambon() {
        return jambon;
    }

    public JCheckBox getMakarouna() {
        return makarouna;
    }

    public JCheckBox getPepsi() {
        return pepsi;
    }

    public JCheckBox getSalade() {
        return salade;
    }

    public JCheckBox getTho() {
        return tho;
    }

    public JCheckBox getThon() {
        return thon;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bo;
    private javax.swing.JCheckBox boga;
    private javax.swing.JButton btnValider;
    private javax.swing.JTextField cin;
    private javax.swing.JLabel e;
    private javax.swing.JCheckBox eau;
    private javax.swing.JLabel esc;
    private javax.swing.JCheckBox escalope;
    private javax.swing.JLabel escth;
    private javax.swing.JCheckBox fromage;
    private javax.swing.JCheckBox fruit;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel jam;
    private javax.swing.JCheckBox jambon;
    private javax.swing.JLabel k;
    private javax.swing.JLabel kms;
    private javax.swing.JCheckBox koskos;
    private javax.swing.JLabel label_mont;
    private javax.swing.JLabel m;
    private javax.swing.JCheckBox makarouna;
    private javax.swing.JTextField nCard;
    private javax.swing.JTextField nbreb;
    private javax.swing.JTextField nbree;
    private javax.swing.JTextField nbrej;
    private javax.swing.JTextField nbrek;
    private javax.swing.JTextField nbrem;
    private javax.swing.JTextField nbrep;
    private javax.swing.JTextField nbrepf;
    private javax.swing.JTextField nbrepm;
    private javax.swing.JTextField nbrepth;
    private javax.swing.JTextField nbres;
    private javax.swing.JTextField nbresc;
    private javax.swing.JTextField nbrethon;
    private javax.swing.JButton pay;
    private javax.swing.JLabel pep;
    private javax.swing.JLabel pepeau;
    private javax.swing.JCheckBox pepsi;
    private javax.swing.JLabel pf;
    private javax.swing.JLabel pfm;
    private javax.swing.JLabel piz;
    private javax.swing.JLabel pth;
    private javax.swing.JLabel s;
    private javax.swing.JCheckBox salade;
    private javax.swing.JLabel th;
    private javax.swing.JCheckBox tho;
    private javax.swing.JCheckBox thon;
    private javax.swing.JTextField txt_montant;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
